ranks:
  mining_rank: true
  placing_rank: true
  online_time_rank: true
  death_rank: false
  switch_interval: 15

storage:
  database: "database.db"
  save_interval: 60

leaderboards:
  mining_rank: "Mining"
  placing_rank: "Placement"
  online_time_rank: "Online Time"
  death_rank: "Death"
  max_leaderboard_size: 10