ranks:
  # Whether to display the mining rank
  mining_rank: true
  # Whether to display the placement rank
  placing_rank: true
  # Whether to display the online time rank
  online_time_rank: true
  # Whether to display the death rank
  death_rank: false
  # The interval of switching ranks on the scoreboard
  switch_interval: 15
  # The regex to ignore specific usernames
  ignore_username_regex: "Input_a_regex_here_to_ignore_specific_usernames"

storage:
  # The filename of local SQLite database file
  database: "database.db"
  # The interval of saving data to the database
  save_interval: 60

leaderboards:
  # The title of the mining rank leaderboard
  mining_rank: "Mining"
  # The title of the placement rank leaderboard
  placing_rank: "Placement"
  # The title of the online time rank leaderboard
  online_time_rank: "Online Time"
  # The title of the death rank leaderboard
  death_rank: "Death"
  # The maximum size of the leaderboard
  max_leaderboard_size: 10