name: PixelRank
version: '1.0-SNAPSHOT'
description: "A plugin that ranks players in multiple values."
main: com.codezhangborui.pixelRank.PixelRank
api-version: '1.20'
commands:
  pixelrank:
    description: "PixelRank commands"
    usage: "/<command> reload"